"""
Pydantic schemas for request/response validation.
"""
from typing import Any, List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class TaskDefinition(BaseModel):
    """Represents a task from the planner."""
    id: int = Field(..., description="Unique task ID")
    title: str = Field(..., description="Task title")
    description: Optional[str] = Field(None, description="Detailed task description")
    tool: str = Field(..., description="Tool to execute (e.g., 'llm')")
    dependencies: List[int] = Field(default_factory=list, description="IDs of tasks this depends on")


class ExecutionPlan(BaseModel):
    """Represents the execution plan generated by the planner."""
    goal: str = Field(..., description="Overall goal statement")
    assumptions: List[str] = Field(default_factory=list, description="Key assumptions made")
    tasks: List[TaskDefinition] = Field(..., description="List of tasks to execute")


class TaskResult(BaseModel):
    """Result from executing a single task."""
    task_id: int = Field(..., description="ID of the executed task")
    title: str = Field(..., description="Task title")
    status: str = Field(..., description="Status: 'completed' or 'failed'")
    output: Any = Field(..., description="Task output")
    error: Optional[str] = Field(None, description="Error message if failed")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentRequest(BaseModel):
    """Request body for the /agent endpoint."""
    request: str = Field(..., description="The user's request to the agent")


class AgentResponse(BaseModel):
    """Response body from the /agent endpoint."""
    success: bool = Field(..., description="Whether execution succeeded")
    execution_plan: ExecutionPlan = Field(..., description="The generated execution plan")
    completed_tasks: List[TaskResult] = Field(..., description="Results from executed tasks")
    assumptions: List[str] = Field(..., description="Key assumptions about the request")
    docx_file: str = Field(..., description="Path to the generated DOCX file")
    summary: str = Field(..., description="Summary of what was accomplished")
    error: Optional[str] = Field(None, description="Error message if execution failed")
